# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: footy_fix
services:
  app:
    image: footy_fix
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/footy_fix
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://postgresql:5432/footy_fix
    ports:
      - 0.0.0.0:4242:4242
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:4242/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      postgresql:
        condition: service_healthy
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql

  nginx:
    image: kaido23/nginx:24.03.03
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 0.0.0.0:443:443
